blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('profile/<slug:slug>/', views.ProfileDetail.as_view(), name='profile_detail'),
]

game/urls.py
from django.urls import path
from game import views
from party import views as p_views

urlpatterns = [
    path("<int:pid>/lobby/", views.lobby, name="lobby"),
    path("<int:pid>/play/", views.play, name="play"),
    path("<int:pid>/play/choose_category", views.choose_category, name="choose_category"),
    path("<int:pid>/play/pick_category", views.pick_category, name="pick_category"),
    path("<int:pid>/play/pick_song", views.pick_song, name="pick_song"),
    path("<int:pid>/play/settings", views.settings, name="settings"),
    path("<int:pid>/play/users", views.users, name="users"),
    path("update_play", views.update_play, name="update_play"),
    path("update_lobby", views.update_lobby, name="update_lobby"),
    path("update_set_device", p_views.update_set_device, name="update_set_device"),
    path("update_search", views.update_search, name="update_search"),
    path("update_categories", views.update_categories, name="update_categories"),
    path("update_like", views.update_like, name="update_like"),
    path("<int:pid>/dashboard/", views.dashboard, name="dashboard"),
]

queue_it_up/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls')),
    path('party/', include('party.urls')),
    path('sesh/', include('game.urls')),
    path('blog/', include('blog.urls')),
    path('spot/', include('spot.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
from django.db import models

game/forms.py
from django import forms
from django.utils.safestring import mark_safe
from party.models import Library, Searches, Devices
from game.fields import ListTextWidget
from django.core.validators import MinValueValidator


class blankForm(forms.Form):
    blank = forms.CharField(label='text', required=False)
    

class chooseCategoryForm(forms.Form):
    cat_choice = forms.ModelChoiceField(
        label = 'Curate the Vibe',
        queryset=Library.objects.all(),
        required=False,
        widget=forms.Select(attrs={'class':'form-control'})
    ) 
    custom = forms.CharField(
        label = 'Create Your Own',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'NAME',}),
        max_length=Library._meta.get_field('name').max_length
    )
    custom_desc = forms.CharField(
        label = 'Create Your Own',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'DESCRIPTION',}),
        max_length=Library._meta.get_field('description').max_length
    )
    artist = forms.CharField(
        label = 'Artist Name',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'ENTER THE NAME OF AN ARTIST',}),
        max_length=Library._meta.get_field('name').max_length
    )
    CHOICES=[('Artist','Artist'),( 'Song','Song')]
    scatt_radio = forms.ChoiceField(
        choices=CHOICES,
        widget=forms.RadioSelect(attrs={'class':'form-check-inline'}),
        initial='Song'
    )

    search = forms.CharField(required = False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Search for Vibes',}))
    result = forms.CharField(label = 'result pk', initial='-1', required = False,widget=forms.TextInput(attrs={'class':'form-control',}))

    def __init__(self,*args,**kwargs):
        self.repo = kwargs.pop('repo')
        super(chooseCategoryForm,self).__init__(*args,**kwargs)
        combined_query = Library.objects.filter(pk__in=self.repo, visible=True) | Library.objects.filter(special=True, visible=True)
        self.fields['cat_choice'].queryset = combined_query.order_by('order','name')


class pickCategoryForm(forms.Form):
    custom = forms.CharField(
        label = 'Create Your Own',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'ENTER SOME WORDS HERE...',}),
        max_length=Library._meta.get_field('name').max_length
    )
    custom_desc = forms.CharField(
        label = 'Create Your Own',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'DESCRIPTION',}),
        max_length=Library._meta.get_field('description').max_length
    )
    search = forms.CharField(
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Search for Vibes',})
    )
    result = forms.CharField(
        label = 'result pk',
        initial='-1',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control',})
    )
    artist = forms.CharField(
        label = 'Artist Name',
        required = False,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'ENTER THE NAME OF AN ARTIST',}),
        max_length=Library._meta.get_field('name').max_length - 15
    )


class searchForm(forms.Form):
    result = forms.CharField(label = 'result pk', initial='-1', required = False,widget=forms.TextInput(attrs={'class':'form-control',}))
    search = forms.CharField(required = False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Search Songs or Artists',}))
    #search = forms.CharField(required=False,widget=forms.TextInput)

    #def __init__(self, *args, **kwargs):
    #    _song_list = kwargs.pop('data_list', None)
    #    super(searchForm, self).__init__(*args, **kwargs)

    # the "name" parameter will allow you to use the same widget more than once in the same
    # form, not setting this parameter differently will cuse all inputs display the
    # same list.
    #    self.fields['search'].widget = ListTextWidget(data_list=_song_list, name='song-list')

class searchResultsForm(forms.Form):
    results = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'form-control'}),queryset=Searches.objects.all(), required=False)
        
    def __init__(self,*args,**kwargs):
        
        self.partyObject = kwargs.pop('partyObject')
        self.userObject = kwargs.pop('userObject')
        super(searchResultsForm,self).__init__(*args,**kwargs)
        self.fields['results'].queryset = Searches.objects.filter(party=self.partyObject, user=self.userObject).order_by('pk')


class settingsForm(forms.Form):

    time = forms.IntegerField(validators=[MinValueValidator(30)])
    device = forms.ModelChoiceField(queryset=Devices.objects.all(), required = False, widget=forms.Select(attrs={'class':'form-control'}))
        
    def __init__(self,*args,**kwargs):
        
        self.partyObject = kwargs.pop('partyObject')
        super(settingsForm,self).__init__(*args,**kwargs)
        self.fields['device'].queryset = Devices.objects.filter(party=self.partyObject)

game/views.py
from django.shortcuts import render
from django.urls import reverse
from background_task import background
from utils.util_auth import check_token
from utils.util_user import (
    get_user,
    check_permission,
    assign_leader,
    reset_users,
    set_user_points,
    reset_user_likes,
    get_like_total,
)
from utils.util_party import (
    get_party,
    clean_up_party,
    get_inactivity,
    set_lib_repo,
    get_results,
    get_totals,
    get_category_choices,
    create_category,
    check_duplicate,
    wait_for_song,
)
from utils.util_device import get_active_device
from utils.util_song import get_bg_color
from django.http import HttpResponseRedirect, JsonResponse
from party.models import Party, Users, Category, Songs, Searches, Devices, Library
from game.forms import (
    blankForm,
    chooseCategoryForm,
    pickCategoryForm,
    searchForm,
    settingsForm,
)
from html import escape
import spotipy
import time
import threading
import random
from queue_it_up.settings import URL, QDEBUG


def lobby(request, pid):
    """Gets Users in Party and Displays them. The Party host has the ability
    to start the party by submitting the form. Submitting the form launches a
    browser window on the system and sets the party to started.

    Parameters:

        - request - web request
        - pid - Primary Key of the Party the User belongs to

    """
    party = get_party(pid)
    if party == -1:
        return HttpResponseRedirect(reverse("index"))
    if get_inactivity(pid, 19):
        clean_up_party(party.pk)
    if request.method == "POST":
        form = blankForm(request.POST)
        if form.is_valid():
            category = Category(name="New queue Coming Soon...", party=party)
            category.save()
            party.lib_repo = set_lib_repo()
            party.started = True
            party.save()
            task = threading.Thread(target=call_task, args=(pid,))
            task.start()
            return HttpResponseRedirect(reverse("play", kwargs={"pid": pid}))
    else:
        form = blankForm(
            initial={
                "text": "blank",
            }
        )
        party = Party.objects.get(pk=pid)
        if party.started:
            return HttpResponseRedirect(reverse("play", kwargs={"pid": pid}))
    users = Users.objects.filter(party=pid, active=True).all()
    names = []
    for user in users:
        names.append(user.icon + " " + user.name)
    current_user = get_user(request, pid)
    if current_user.isHost:
        device = get_active_device(party)
    else:
        device = {}
    context = {
        "party": party,
        "names": names,
        "access": current_user.isHost,
        "form": form,
        "URL": URL,
        "device": device,
    }
    return render(request, "game/lobby.html", context)


def update_lobby(request):
    """Ajax request to update the users on the lobby page. Returns an updated
    party size, list of names, and whether the party is started or inactive.

    Parameters:

        - request - web request

    """
    pid = request.GET.get("pid", None)
    party = Party.objects.get(pk=pid)
    if get_inactivity(pid, 19):
        clean_up_party(party.pk)
    users = Users.objects.filter(party=pid, active=True).all()
    names = []
    for user in users:
        names.append(user.icon + " " + user.name)
    data = {
        "size": users.count(),
        "started": party.started,
        "names": names,
        "inactive": party.active,
    }
    return JsonResponse(data)


def call_task(pid):
    """Thread used to run background task, prevents delay in redirect while
    calling the task

    Parameters:
        - pid - Primary Key of the Party the User belongs to

    """
    run_game.now(pid)


def play(request, pid):
    """Gets the song playing and displays it with the category and party info.
    Form Post will increment/decrement the playing song's likes.

    Parameters:

        - request - web request
        - pid - Primary Key of the Party the User belongs to

    """
    party = get_party(pid)
    user = get_user(request, pid)
    if party == -1 or user == -1:
        return HttpResponseRedirect(reverse("index"))
    song = Songs.objects.filter(category__party=party, state="playing").first()
    if song:
        category = song.category
    else:
        song = Songs(art="lull")
        category = Category.objects.filter(party=party, roundNum=0).first()

    last_category = Category.objects.filter(
        party=party, roundNum=party.roundTotal
    ).first()
    full = False
    if last_category:
        full = last_category.full

    results = get_results(party)
    totals = get_totals(party)

    if user.isHost:
        device = get_active_device(party)
    else:
        device = {}

    context = {
        "party": party,
        "user": user,
        "category": category,
        "song": song,
        "results": results,
        "totals": totals,
        "URL": URL,
        "full": full,
        "device": device,
    }

    return render(request, "game/play.html", context)


def update_play(request):
    """Ajax request made by general user to update the play page with the
    latest info (i.e. current song and category).
    Returns data to ensure page reflects the current play state and is showing
    latest info.

    Parameters:

        - request - web request

    """
    pid = request.GET.get("pid", None)
    party = Party.objects.get(pk=pid)
    if get_inactivity(pid, 19):
        party.active = False

    user = get_user(request, pid)

    song = Songs.objects.filter(category__party=party, state="playing").first()
    if song:
        category = song.category
    else:
        song = Songs(art="lull")
        category = Category.objects.filter(party=party, roundNum=0).first()

    last_category = Category.objects.filter(
        party=party, roundNum=party.roundTotal
    ).first()
    full = False
    if last_category:
        full = last_category.full

    results = get_results(party)
    totals = get_totals(party)

    party_info = {
        "device_error": str(party.device_error),
        "name": party.name,
        "state": party.state,
        "joinCode": party.joinCode,
        "inactive": not party.active,
    }
    user_info = {
        "isHost": str(user.isHost),
        "hasPicked": str(user.hasPicked),
        "turn": user.turn,
        "hasLiked": str(user.hasLiked),
        "hasDislike": str(user.hasSkip),
        "user": user.pk,
    }
    try:
        leader = category.leader.name
    except Exception:
        leader = ""
    category_info = {
        "name": category.name,
        "leader": leader,
        "full": full,
    }
    try:
        song_user = song.user.pk
    except Exception:
        song_user = -1

    song_info = {
        "name": song.name,
        "title": song.title,
        "artist": song.artist,
        "link": song.link,
        "user": song_user,
        "art": song.art,
        "color": song.color,
    }
    data = {
        "party": party_info,
        "user": user_info,
        "category": category_info,
        "song": song_info,
        "results": results,
        "totals": totals,
    }
    return JsonResponse(data)


def update_like(request):
    """Ajax call to increment or Decrement the like field of a Song object
        based on the request. Prevents user from liking one song multiple times.

    Parameters:

        - request - web request

    """
    pid = request.GET.get("pid", None)
    like = request.GET.get("like", None)
    action = request.GET.get("action", None)
    user = get_user(request, pid)
    if like == "true":
        if action == "like_icon":
            user.hasLiked = True
            user.hasSkip = False
        else:
            user.hasLiked = False
            user.hasSkip = False
    else:
        if action == "dislike_icon":
            user.hasLiked = False
            user.hasSkip = True
        else:
            user.hasLiked = False
            user.hasSkip = False
    user.save()
    print(
        QDEBUG,
        user.name,
        ": Set User Like: ",
        user.hasLiked,
        " Set User Dislike: ",
        user.hasSkip,
    )
    data = {}
    return JsonResponse(data)


@background()
def run_game(pid):
    """Background Task to update the game logic and trigger the song thread

    Parameters:

        - pid - primary key of party

    """
    while Party.objects.filter(pk=pid, active=True).first():
        if get_inactivity(pid, 19):
            clean_up_party(pid)

        if Party.objects.filter(pk=pid, active=True, state="assign").first() or (
            Party.objects.filter(pk=pid, active=True, state="choose_category").first()
            and not Users.objects.filter(
                turn="picking", party__pk=pid, active=True
            ).first()
        ):
            party = Party.objects.get(pk=pid)
            assign_leader(party)
            party.state = "choose_category"
            party.save()
            print(QDEBUG, "Set state to choose category: ", party.state)

        if (
            Party.objects.filter(pk=pid, active=True, state="pick_song").first()
            and not Users.objects.filter(
                hasPicked=False, party__pk=pid, active=True
            ).all()
        ):
            party = Party.objects.get(pk=pid)
            category = Category.objects.filter(
                party=party, roundNum=party.roundTotal
            ).first()
            category.full = True
            category.save()
            print(QDEBUG, "Set Category to Full: ", category.full)
            party.state = "assign"
            party.save()
            print(QDEBUG, "Set state to assign: ", party.state)
            reset_users(party)

        party = Party.objects.get(pk=pid)
        if Party.objects.filter(
            pk=pid, active=True, device_error=False, thread=False
        ).first() and Songs.objects.filter(
            category__party__pk=pid,

game/templates/game/chooseCat.html
<!DOCTYPE html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% extends "base.html" %}
{% block page_content %}

	<script type="text/javascript">
		window.onload = function() {
			var x = document.getElementById("id_cat_choice").selectedIndex;
			var y = document.getElementById("id_cat_choice").options;		
			var z = y[x].text;
			var box = '';
			var label = '';
			var info = '';
			var radio0 = document.getElementById('radio0');
			var radio1 = document.getElementById('radio1');

			radio0.style.display = 'none';
			radio1.style.display = 'none';
			
			if (z == 'Custom'){
				box = '{{ form.custom }}';
				label = '{{ form.custom.label }}';
			}
			else if(z == 'Songs by this Artist'){
				box = '{{ form.artist }}';
				label = '{{ form.artist.label }}';
			}
			else if (z == 'Scattergories'){
				info = 'Songs where the Song or Artist name begins with a Randomly Generated Letter';
				radio0.style.display = 'initial';
				radio1.style.display = 'initial';
			}
			document.getElementById('info').innerHTML = info;
			document.getElementById('custom').innerHTML = box;
			document.getElementById('label').innerHTML = label;
		};
		$(document).ready(function() {
			$('#id_cat_choice').change(function() {
			var x = document.getElementById("id_cat_choice").selectedIndex;
			var y = document.getElementById("id_cat_choice").options;		
			var z = y[x].text;
			var box = '';
			var label = '';
			var info = '';
			var radio0 = document.getElementById('radio0');
			var radio1 = document.getElementById('radio1');
			radio0.style.display = 'none';
			radio1.style.display = 'none';

			if (z == 'Custom'){
				box = '{{ form.custom }}';
				label = '{{ form.custom.label }}';
			}
			else if(z == 'Songs by this Artist'){
				box = '{{ form.artist }}';
				label = '{{ form.artist.label }}';
			}
			else if (z == 'Scattergories'){
				info = 'Songs where the Song or Artist name begins with a Randomly Generated Letter';
				radio0.style.display = 'initial';
				radio1.style.display = 'initial';
			}
			document.getElementById('custom').innerHTML = box;
			document.getElementById('label').innerHTML = label;
			document.getElementById('info').innerHTML = info;
			})
		});
	</script>

	<div class = "container" style="width:90%">
		<form action="" method="post">
			{% csrf_token %}

			<div class="row">
				<h6>{{ form.cat_choice.label }}</h6>			
				{{ form.cat_choice }}
				<small class="form-text text-muted" id=info></small>
			</div>

			<div class="row">
				<div id="radio0" style='display:none;'>{{ form.scatt_radio.0 }}</div>
				<div class = "pl-4" id="radio1" style='display:none;'>{{ form.scatt_radio.1 }}</div>			
			</div> 

			<div class="row">
				<h6 class="pt-2" id="label"></h6>
			</div>

			<div class="row" id="custom"> 
			</div>

			<div class = "pt-2 pb-2 text-right">
				<input type="submit" class="btn btn-outline-primary" name="back" value="Back"></input>
				<input type="submit" class="btn btn-outline-primary" value="Submit"></input>
			</div>
				
			{% if invalid %}
			<div class=" row alert alert-info">
				select a vibe before submitting
			</div>
			{% endif %}

		</form>	
	</div>
{% endblock %}

game/templates/game/choose_category.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block page_content %}
	<script type="text/javascript">
		window.onload = function() {
			var x = document.getElementById("id_cat_choice").selectedIndex;
			var y = document.getElementById("id_cat_choice").options;		
			var z = y[x].text;
			var box = '';
			var label = '';
			var info = '';
			var radio0 = document.getElementById('radio0');
			var radio1 = document.getElementById('radio1');

			radio0.style.display = 'none';
			radio1.style.display = 'none';
			
			if (z == 'Custom'){
				box = '{{ form.custom }}';
				label = '{{ form.custom.label }}';
			}
			else if(z == 'Songs by this Artist'){
				box = '{{ form.artist }}';
				label = '{{ form.artist.label }}';
			}
			else if (z == 'Scattergories'){
				info = 'Songs where the Song or Artist name begins with a Randomly Generated Letter';
				radio0.style.display = 'initial';
				radio1.style.display = 'initial';
			}
			document.getElementById('info').innerHTML = info;
			document.getElementById('custom').innerHTML = box;
			document.getElementById('label').innerHTML = label;
		};
		$(document).ready(function() {
			$('#id_cat_choice').change(function() {
			var x = document.getElementById("id_cat_choice").selectedIndex;
			var y = document.getElementById("id_cat_choice").options;		
			var z = y[x].text;
			var box = '';
			var label = '';
			var info = '';
			var radio0 = document.getElementById('radio0');
			var radio1 = document.getElementById('radio1');
			radio0.style.display = 'none';
			radio1.style.display = 'none';

			if (z == 'Custom'){
				box = '{{ form.custom }}';
				label = '{{ form.custom.label }}';
			}
			else if(z == 'Songs by this Artist'){
				box = '{{ form.artist }}';
				label = '{{ form.artist.label }}';
			}
			else if (z == 'Scattergories'){
				info = 'Songs where the Song or Artist name begins with a Randomly Generated Letter';
				radio0.style.display = 'initial';
				radio1.style.display = 'initial';
			}
			document.getElementById('custom').innerHTML = box;
			document.getElementById('label').innerHTML = label;
			document.getElementById('info').innerHTML = info;
			});
		});
	</script>

	<div class = "container form-width ps-3 pe-3" >
		<form action="" method="post">
			{% csrf_token %}

			<div class="row">
				<h6>{{ form.cat_choice.label }}</h6>			
				{{ form.cat_choice }}
				<small class="form-text text-muted" id=info></small>
			</div>

			<div class="row">
				<div id="radio0" style='display:none;'>{{ form.scatt_radio.0 }}</div>
				<div id="radio1" style='display:none;'>{{ form.scatt_radio.1 }}</div>			
			</div> 

			<div class="row">
				<h6 class="pt-2" id="label"></h6>
			</div>

			<div class="row" id="custom"> 
			</div>

			<div class = "pt-2 pb-2 text-end">
				<a href="{% url 'play' pid=party.pk %}" id="play" class="btn btn-outline-light btn-lg block" style= "border:3px solid black; border-radius:16px; color:black">Back</a>
				<input type="submit" class="btn btn-outline-light btn-lg block" style= "border:3px solid black; border-radius:16px; color:black" value="Submit"></input>
			</div>
				
			{% if invalid %}
			<div class="row alert alert-info">
				select a vibe before submitting
			</div>
			{% endif %}
		</form>		
	</div>
{% endblock %}

game/templates/game/searchResults.html
<!DOCTYPE html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% extends "base.html" %}
{% block page_content %}

<script type="text/javascript">
	
	$(document).ready(function() {
		$('#id_results').change(function() {
		var x = document.getElementById("id_results").selectedIndex;
		var y = document.getElementById("id_results").options;		
		var z = y[x].index;
		if(z==0){
			//var album = "https://drive.google.com/uc?id=1U30oo8mIVzZnn4pIl06SH1StSsBpaq7F"
			{% load static %}
			var album = "{% static 'images/queue_it_to_it_brah.png' %}"
		}
		else if(z==1){
			var album = '{{albumSearch.0.art}}';
		}
		else if(z==2){
			var album = '{{albumSearch.1.art}}';
		}
		else if(z==3){
			var album = '{{albumSearch.2.art}}';
		}
		else if(z==4){
			var album = '{{albumSearch.3.art}}';
		}
		else if(z==5){
			var album = '{{albumSearch.4.art}}';
		}
		else if(z==6){
			var album = '{{albumSearch.5.art}}';
		}
		else if(z==7){
			var album = '{{albumSearch.6.art}}';
		}
		else if(z==8){
			var album = '{{albumSearch.7.art}}';
		}
		else if(z==9){
			var album = '{{albumSearch.8.art}}';
		}
		else if(z==10){
			var album = '{{albumSearch.9.art}}';
		}
		else if(z==11){
			var album = '{{albumSearch.10.art}}';
		}
		else if(z==12){
			var album = '{{albumSearch.11.art}}';
		}
		else if(z==13){
			var album = '{{albumSearch.12.art}}';
		}
		else if(z==14){
			var album = '{{albumSearch.13.art}}';
		}
		else if(z==15){
			var album = '{{albumSearch.14.art}}';
		}
		else {
			{% load static %}
			var album = "{% static 'images/queue_it_to_it_brah.png' %}"
		}
		document.getElementById('output').innerHTML = '<img src="'+ album + '" class="img-thumbnail" width="200" height="200" alt="...">';
		})
	});

</script>
	
	<div class="container text-center">	
		<h6>Search Results</h6>
		<form action="" method="post">
			{% csrf_token %}
			<div id="output", class ="pt-1"></div>																											
			<div class = "pt-3" wrap="hard">
				{{ form.results }}	
			</div>
						
			{% if invalid and isArtist %}
			<div class="alert alert-info">
				select a valid artist
			</div>	
			{% elif invalid and not isArtist  %}
			<div class="alert alert-info">
				Select a Valid Song
			</div>
			{% endif %}
					
			<div class = "pt-2">
				<input type="submit" class="btn btn-outline-primary" name="back"  value="Back">
				<input type="submit" class="btn btn-outline-primary" name="add2q" value="Add to Queue">
			</div>
		</form>
	</div>

{% endblock %}

game/templates/game/search_results.html
<!DOCTYPE html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% extends "base.html" %}
{% block page_content %}

<script type="text/javascript">
	
	$(document).ready(function() {
		$('#id_results').change(function() {
		var x = document.getElementById("id_results").selectedIndex;
		var y = document.getElementById("id_results").options;		
		var z = y[x].index;
		if(z==0){
			//var album = "https://drive.google.com/uc?id=1U30oo8mIVzZnn4pIl06SH1StSsBpaq7F"
			{% load static %}
			var album = "{% static 'images/queue_it_to_it_brah.png' %}"
		}
		else if(z==1){
			var album = '{{albumSearch.0.art}}';
		}
		else if(z==2){
			var album = '{{albumSearch.1.art}}';
		}
		else if(z==3){
			var album = '{{albumSearch.2.art}}';
		}
		else if(z==4){
			var album = '{{albumSearch.3.art}}';
		}
		else if(z==5){
			var album = '{{albumSearch.4.art}}';
		}
		else if(z==6){
			var album = '{{albumSearch.5.art}}';
		}
		else if(z==7){
			var album = '{{albumSearch.6.art}}';
		}
		else if(z==8){
			var album = '{{albumSearch.7.art}}';
		}
		else if(z==9){
			var album = '{{albumSearch.8.art}}';
		}
		else if(z==10){
			var album = '{{albumSearch.9.art}}';
		}
		else if(z==11){
			var album = '{{albumSearch.10.art}}';
		}
		else if(z==12){
			var album = '{{albumSearch.11.art}}';
		}
		else if(z==13){
			var album = '{{albumSearch.12.art}}';
		}
		else if(z==14){
			var album = '{{albumSearch.13.art}}';
		}
		else if(z==15){
			var album = '{{albumSearch.14.art}}';
		}
		else {
			{% load static %}
			var album = "{% static 'images/queue_it_to_it_brah.png' %}"
		}
		document.getElementById('output').innerHTML = '<img src="'+ album + '" class="img-thumbnail" width="200" height="200" alt="...">';
		})
	});

</script>
	
	<div class="container text-center">	
		<h6>Search Results</h6>
		<form action="" method="post">
			{% csrf_token %}
			<div id="output", class ="pt-1"></div>																											
			<div class = "pt-3" wrap="hard">
				{{ form.results }}	
			</div>
						
			{% if invalid and isArtist %}
			<div class="alert alert-info">
				select a valid artist
			</div>	
			{% elif invalid and not isArtist  %}
			<div class="alert alert-info">
				Select a Valid Song
			</div>
			{% endif %}
					
			<div class = "pt-2">
				<input type="submit" class="btn btn-outline-light btn-lg block" style= "border:3px solid black; border-radius:16px; color:black" name="back"  value="Back">
				<input type="submit" class="btn btn-outline-light btn-lg block" style= "border:3px solid black; border-radius:16px; color:black" name="add2q" value="Add to Queue">
			</div>
		</form>
	</div>

{% endblock %}